[package]
name = "gaiku-baker-voxel"
version = "0.1.0"
authors = ["norman784 <normanpaniagua@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gaiku-common = { path = "../../plugins/gaiku-common" }
