name:                Rust

on:
  push:
    branches:        [ master ]
  pull_request:
    branches:        [ master ]

env:
  CARGO_TERM_COLOR:  always

jobs:
  build:

    runs-on:         ubuntu-latest

    steps:
      - name:        Checkout
        uses:        actions/checkout@v2
      - name:        Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y gcc pkg-config openssl libasound2-dev cmake build-essential python3 libfreetype6-dev libexpat1-dev libxcb-composite0-dev libssl-dev libx11-dev pulseaudio
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: cargo
      - name:        Build
        uses:        actions-rs/cargo@v1
        with:
          command: build
          toolchain: nightly
          args:    --verbose --all-features
      - name:        Test
        uses:        actions-rs/cargo@v1
        with:
          command: test
          toolchain: nightly
          args:    --verbose --all-features
